<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-08-14T15:05:00 IST" name="Suite" finished-at="2020-08-14T15:05:07 IST" duration-ms="6909">
    <groups>
      <group name="Regression">
        <method signature="LibraryTest.LibraryPOST()[pri:1, instance:libraryService.LibraryTest@1f59a598]" name="LibraryPOST" class="libraryService.LibraryTest"/>
        <method signature="LibraryTest.LibraryDelete()[pri:3, instance:libraryService.LibraryTest@1f59a598]" name="LibraryDelete" class="libraryService.LibraryTest"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2020-08-14T15:05:00 IST" name="Library" finished-at="2020-08-14T15:05:07 IST" duration-ms="6909">
      <class name="libraryService.LibraryTest">
        <test-method is-config="true" signature="initialize()[pri:0, instance:libraryService.LibraryTest@1f59a598]" started-at="2020-08-14T15:05:00 IST" name="initialize" finished-at="2020-08-14T15:05:02 IST" duration-ms="1695" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="LibraryPOST()[pri:1, instance:libraryService.LibraryTest@1f59a598]" started-at="2020-08-14T15:05:02 IST" name="LibraryPOST" finished-at="2020-08-14T15:05:07 IST" duration-ms="4904" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LibraryPOST -->
        <test-method signature="LibraryDelete()[pri:3, instance:libraryService.LibraryTest@1f59a598]" started-at="2020-08-14T15:05:07 IST" name="LibraryDelete" finished-at="2020-08-14T15:05:07 IST" depends-on-methods="libraryService.LibraryTest.LibraryPOST" duration-ms="209" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [book is successfully deleted] but found [books is successfully deleted]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [book is successfully deleted] but found [books is successfully deleted]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at libraryService.LibraryTest.LibraryDelete(LibraryTest.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LibraryDelete -->
      </class> <!-- libraryService.LibraryTest -->
    </test> <!-- Library -->
  </suite> <!-- Suite -->
</testng-results>
